language:
  - cpp

os: linux
dist: bionic

jobs:
  include:
    - name: build without external dependencies
      os: linux
      dist: bionic

    - name: build with netcdf
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libnetcdf-dev
      env: 
        - CMAKE_ARG="-DFTK_USE_NETCDF=ON"

    - name: build with hdf5
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libhdf5-dev
      env: 
        - CMAKE_ARG="-DFTK_USE_HDF5=ON"

    - name: build with mpi
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libmpich-dev
      env: 
        - CMAKE_ARG="-DFTK_USE_MPI=ON"

before_script:
  - mkdir build
  - cd build
  - cmake .. -DFTK_BUILD_TESTS=ON ${CMAKE_ARG}
  - cmake --build .

script: 
  - ctest

notifications:
  email:
    - guohanqi@gmail.com
