language:
  - cpp

os: linux
dist: bionic

jobs:
  include:
    - name: build without external dependencies
      os: linux
      dist: bionic

    - name: build with netcdf
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libnetcdf-dev

before_script:
  - mkdir build
  - cd build
  - cmake .. -DFTK_BUILD_TESTS=ON -DFTK_USE_NETCDF=ON
  - cmake --build .

script: 
  - cd build
  - ctest

notifications:
  email:
    - guohanqi@gmail.com
