language:
  - cpp

os: linux
dist: bionic

jobs:
  include:
    - name: build without external dependencies (linux)
      os: linux
      dist: bionic

    - name: build without external dependencies (osx)
      os: osx
      osx_image: xcode11

    - name: build with mpsolve (linux)
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libgmp-dev
      before_install:
        - sh tests/travis/install-mpsolve.sh
      env:
        - CMAKE_ARG="-DFTK_USE_MPSolve=ON -DMPSolve_INCLUDE_DIR=/tmp/MPSolve-3.2.1/include -DMPSolve_LIBRARY=/tmp/MPSolve-3.2.1/lib/libmps.so"

    - name: build with netcdf (linux)
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libnetcdf-dev
      env: 
        - CMAKE_ARG="-DFTK_USE_NETCDF=ON"

    - name: build with hdf5 (linux)
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libhdf5-dev
      env: 
        - CMAKE_ARG="-DFTK_USE_HDF5=ON"

    - name: build with vtk (linux)
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libvtk7-dev
      env: 
        - CMAKE_ARG="-DFTK_USE_VTK=ON"
    
    - name: build with netcdf, hdf5, and vtk (linux)
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libnetcdf-dev
            - libhdf5-dev
            - libvtk7-dev
      env: 
        - CMAKE_ARG="-DFTK_USE_MPI=ON -DFTK_USE_HDF5=ON -DFTK_USE_VTK=ON"

    - name: build with mpsolve, netcdf, hdf5, and vtk (linux)
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libnetcdf-dev
            - libhdf5-dev
            - libvtk7-dev
      before_install:
        - sh tests/travis/install-mpsolve.sh
      env:
        - CMAKE_ARG="-DFTK_USE_MPI=ON -DFTK_USE_HDF5=ON -DFTK_USE_VTK=ON -DFTK_USE_MPSolve=ON -DMPSolve_INCLUDE_DIR=/tmp/MPSolve-3.2.1/include -DMPSolve_LIBRARY=/tmp/MPSolve-3.2.1/lib/libmps.so"

    - name: build with mpich (osx)
      os: osx
      sudo: required
      before_install:
        - brew install mpich
      osx_image: xcode11

    - name: build with mpich (linux)
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libmpich-dev
      env: 
        - CMAKE_ARG="-DFTK_USE_MPI=ON"

    - name: build with openmpi (linux)
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libopenmpi-dev
      env: 
        - CMAKE_ARG="-DFTK_USE_MPI=ON"

    - name: build with mpsolve, netcdf, hdf5, vtk, and openmpi (linux)
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libnetcdf-dev
            - libhdf5-dev
            - libvtk7-dev
            - libopenmpi-dev
      before_install:
        - sh tests/travis/install-mpsolve.sh
      env: 
        - CMAKE_ARG="-DFTK_USE_MPI=ON -DFTK_USE_HDF5=ON -DFTK_USE_VTK=ON -DFTK_USE_MPSolve=ON -DMPSolve_INCLUDE_DIR=/tmp/MPSolve-3.2.1/include -DMPSolve_LIBRARY=/tmp/MPSolve-3.2.1/lib/libmps.so"

before_script:
  - mkdir build
  - cd build
  - cmake .. -DFTK_BUILD_TESTS=ON ${CMAKE_ARG}
  - cmake --build .

script: 
  - ctest

notifications:
  email:
    - guohanqi@gmail.com
