language:
  - cpp

jobs:
  include:
    - name: build without external dependencies
      os: linux
      dist: bionic
      script: 
      - mkdir build
      - cd build
      - cmake .. -DFTK_BUILD_TESTS=ON
      - cmake --build .
      - ctest
    - name: build with netcdf
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libnetcdf-dev
      script: 
      - mkdir build
      - cd build
      - cmake .. -DFTK_BUILD_TESTS=ON -DFTK_USE_NETCDF=ON
      - cmake --build .
      - ctest

notifications:
  email:
    - guohanqi@gmail.com
