language:
  - cpp

jobs:
  include:
    - name: build without external dependencies
      os: linux
      script: 
      - mkdir build
      - cd build
      - cmake .. -DFTK_BUILD_TESTS=ON
      - cmake --build .
      - ctest

notifications:
  email:
    - guohanqi@gmail.com
